#shared stuff between prod and dev

version: "3.0"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    image: docker pull sujoy95/docker-node-fcc:latest
    environment:
      - PORT=3000
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    volumes:
      - mongo-db-data:/data/db

  redis:
    image: redis

volumes:
  mongo-db-data:
